name: testcase

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  buildandpush:
    name: Build testcase image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build testcase image
        run: make testcase

      - name: Push to Github packages
        env:
          GITHUB_IMAGE_NAME: docker.pkg.github.com/${{ github.repository }}/testcase
        run: |
          echo ${{ secrets.GPR_PASS }} | docker login docker.pkg.github.com -u ${{ secrets.GPR_USER }} --password-stdin
          docker tag testcase:${GITHUB_SHA} ${GITHUB_IMAGE_NAME}:${GITHUB_SHA}
          docker push ${GITHUB_IMAGE_NAME}:${GITHUB_SHA}

      - name: Push latest to Github packages
        if: ${{ github.ref == 'refs/heads/main'}}
        env:
          GITHUB_IMAGE_NAME: docker.pkg.github.com/${{ github.repository }}/testcase
        run: |
          echo ${{ secrets.GPR_PASS }} | docker login docker.pkg.github.com -u ${{ secrets.GPR_USER }} --password-stdin
          docker tag testcase:${GITHUB_SHA} ${GITHUB_IMAGE_NAME}:latest
          docker push ${GITHUB_IMAGE_NAME}:latest

      - name: Push to Coding Artifacts
        if: ${{ github.repository == 'nocalhost/nocalhost' }}
        env:
          CODING_IMAGE_NAME: codingcorp-docker.pkg.coding.net/nocalhost/public/testcase
        run: |
          echo ${{ secrets.CODING_ARTIFACTS_PASS }} | docker login codingcorp-docker.pkg.coding.net -u ${{ secrets.CODING_ARTIFACTS_USER }} --password-stdin
          docker tag testcase:${GITHUB_SHA} ${CODING_IMAGE_NAME}:${GITHUB_SHA}
          docker push ${CODING_IMAGE_NAME}:${GITHUB_SHA}

      - name: Push latest to Coding Artifacts
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'nocalhost/nocalhost' }}
        env:
          CODING_IMAGE_NAME: codingcorp-docker.pkg.coding.net/nocalhost/public/testcase
        run: |
          echo ${{ secrets.CODING_ARTIFACTS_PASS }} | docker login codingcorp-docker.pkg.coding.net -u ${{ secrets.CODING_ARTIFACTS_USER }} --password-stdin
          docker tag nocalhost-dep:${GITHUB_SHA} ${CODING_IMAGE_NAME}:latest
          docker push ${CODING_IMAGE_NAME}:latest

      - name: Push latest tag to Coding Artifacts
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'nocalhost/nocalhost' && startsWith(github.ref, 'refs/tags/v')}}
        env:
          CODING_IMAGE_NAME: codingcorp-docker.pkg.coding.net/nocalhost/public/testcase
        run: |
          echo ${{ secrets.CODING_ARTIFACTS_PASS }} | docker login codingcorp-docker.pkg.coding.net -u ${{ secrets.CODING_ARTIFACTS_USER }} --password-stdin
          docker tag testcase:${GITHUB_SHA} ${CODING_IMAGE_NAME}:${GITHUB_REF##*/}
          docker push ${CODING_IMAGE_NAME}:${GITHUB_REF##*/}
